name: Code Quality Checks
on:
  push:

jobs:
  code_quality_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Run code quality checks
        run: |
          npm run lint

      - name: sonar-quality-gate
        uses: dieuhd/sonar-quality-gate@v1
        with:
          sonar_host: ${{ secrets.SONAR_HOST }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          project_key: ${{ secrets.SONAR_PROJECT_KEY }}
          project_name: ${{ secrets.SONAR_PROJECT_NAME }}
          project_version: ${{ secrets.SONAR_PROJECT_VERSION }}
          branch_name: ${{ github.ref }}
